vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: '%product_attachments%'
           upload_destination: '%kernel.project_dir%/public%product_attachments%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: false
           delete_on_remove: false
       users:
           uri_prefix: '/users'
           upload_destination: '%kernel.project_dir%/public/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: false
           delete_on_remove: false
