version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommercedev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ../ecommercedev:/var/lib/mysql
    networks:
      - ecommerce-network

  web:
    image: ecommerce
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
    depends_on:
      - db
    networks:
      - ecommerce-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - ecommerce-network

volumes:
  db_data:

networks:
  ecommerce-network:
    driver: bridge
