
version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommercedev
    volumes:
      - ../db :/var/lib/mysql
      - ../ecommercedev.sql:/docker-entrypoint-initdb.d/ecommercedev.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - ecommerce-network

  web:
    image: fyleeds/ecommerce:v2
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - ecommerce-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

